/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    EditInformation: typeof import('./src/components/EditInformation.vue')['default']
    Google: typeof import('./src/components/Google.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    LowerFloorSeats: typeof import('./src/components/LowerFloorSeats.vue')['default']
    MainFloorSeats: typeof import('./src/components/MainFloorSeats.vue')['default']
    ReservationsTable: typeof import('./src/components/ReservationsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeatCalendar: typeof import('./src/components/SeatCalendar.vue')['default']
    SignupForm: typeof import('./src/components/SignupForm.vue')['default']
    UpperFloorSeats: typeof import('./src/components/UpperFloorSeats.vue')['default']
    UsersTable: typeof import('./src/components/UsersTable.vue')['default']
    WalkIn: typeof import('./src/components/WalkIn.vue')['default']
  }
}
