/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/login': RouteRecordInfo<'/admin/login', '/admin/login', Record<never, never>, Record<never, never>>,
    '/admin/reservations': RouteRecordInfo<'/admin/reservations', '/admin/reservations', Record<never, never>, Record<never, never>>,
    '/admin/staffs': RouteRecordInfo<'/admin/staffs', '/admin/staffs', Record<never, never>, Record<never, never>>,
    '/admin/statistics': RouteRecordInfo<'/admin/statistics', '/admin/statistics', Record<never, never>, Record<never, never>>,
    '/admin/users': RouteRecordInfo<'/admin/users', '/admin/users', Record<never, never>, Record<never, never>>,
    '/admin/walkins': RouteRecordInfo<'/admin/walkins', '/admin/walkins', Record<never, never>, Record<never, never>>,
    '/floor2': RouteRecordInfo<'/floor2', '/floor2', Record<never, never>, Record<never, never>>,
    '/floor4': RouteRecordInfo<'/floor4', '/floor4', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/myreservations': RouteRecordInfo<'/myreservations', '/myreservations', Record<never, never>, Record<never, never>>,
    '/signup': RouteRecordInfo<'/signup', '/signup', Record<never, never>, Record<never, never>>,
    '/staff/': RouteRecordInfo<'/staff/', '/staff', Record<never, never>, Record<never, never>>,
    '/staff/login': RouteRecordInfo<'/staff/login', '/staff/login', Record<never, never>, Record<never, never>>,
    '/staff/reservations': RouteRecordInfo<'/staff/reservations', '/staff/reservations', Record<never, never>, Record<never, never>>,
    '/staff/users': RouteRecordInfo<'/staff/users', '/staff/users', Record<never, never>, Record<never, never>>,
    '/staff/walkins': RouteRecordInfo<'/staff/walkins', '/staff/walkins', Record<never, never>, Record<never, never>>,
  }
}
